version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.local
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - NODE_ENV=development
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb+srv://ksaunibliss:LGaRwEasIMDN1M2x@cluster0.lbc8x6q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - FRONTEND_URL=http://localhost
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
