version: '3.8'

services:
  # Client - builds inside container (no pre-build needed)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped

  # Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb+srv://ksaunibliss:LGaRwEasIMDN1M2x@cluster0.lbc8x6q.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - FRONTEND_URL=https://ksaunibliss.com
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
